import { useState, useMemo } from 'react';
import type { UseWorkflowReturn } from '@/hooks/useWorkflow';
import { getPlatform, getFormat } from '@/data/platforms';
import type { ApprovalDecision, PlatformId } from '@/types';
import {
  CheckCircle2,
  XCircle,
  RotateCcw,
  Clock,
  Lock,
  CheckSquare,
  ListChecks,
  FileCheck,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

const DECISION_CONFIG: Record<ApprovalDecision, { label: string; icon: LucideIcon; color: string; bg: string }> = {
  pending: { label: 'Pending', icon: Clock, color: '#94A3B8', bg: '#F1F5F9' },
  approved: { label: 'Approved', icon: CheckCircle2, color: '#10B981', bg: '#ECFDF5' },
  rejected: { label: 'Rejected', icon: XCircle, color: '#EF4444', bg: '#FEF2F2' },
  revisions: { label: 'Needs Revision', icon: RotateCcw, color: '#F59E0B', bg: '#FFFBEB' },
};

const REVIEW_CHECKLIST = [
  { id: 'brand', label: 'Content aligns with brand voice and guidelines' },
  { id: 'accuracy', label: 'All claims, data, and references are accurate' },
  { id: 'format', label: 'Format matches platform requirements (dimensions, length)' },
  { id: 'tone', label: 'Tone is appropriate for the target audience' },
  { id: 'cta', label: 'Call to action is clear and actionable' },
  { id: 'assets', label: 'Supporting assets (visuals, thumbnails) are ready' },
];

interface WeeklyApprovalViewProps {
  workflow: UseWorkflowReturn;
}

export function WeeklyApprovalView({ workflow }: WeeklyApprovalViewProps) {
  const { approvalBatches, setApprovalDecision, closeBatch, pendingApprovals } = workflow;
  const [activeBatchId, setActiveBatchId] = useState(
    approvalBatches.find((b) => b.status === 'open')?.id || approvalBatches[0]?.id || ''
  );
  const [reviewerName, setReviewerName] = useState('');
  const [checklistState, setChecklistState] = useState<Record<string, boolean>>({});

  const activeBatch = useMemo(
    () => approvalBatches.find((b) => b.id === activeBatchId) || approvalBatches[0],
    [approvalBatches, activeBatchId]
  );

  if (!activeBatch) return null;

  const decisionCounts = activeBatch.items.reduce(
    (acc, item) => {
      acc[item.decision] = (acc[item.decision] || 0) + 1;
      return acc;
    },
    {} as Record<ApprovalDecision, number>
  );

  const allChecked = REVIEW_CHECKLIST.every((c) => checklistState[c.id]);

  const handleDecision = (contentId: string, decision: ApprovalDecision) => {
    setApprovalDecision(activeBatch.id, contentId, decision, reviewerName || 'Reviewer', '');
  };

  const handleCloseBatch = () => {
    closeBatch(activeBatch.id);
  };

  return (
    <div className="p-8 max-w-6xl mx-auto">
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-slate-900 mb-1">Weekly Approval</h2>
        <p className="text-sm text-slate-500">
          One weekly pass to review, approve, or reject all content generated by the daily workflow.
          Only approved content moves to scheduling and handoff.
        </p>
      </div>

      {/* Batch Selector */}
      <div className="flex items-center gap-2 mb-6">
        {approvalBatches.map((batch) => {
          const isActive = batch.id === activeBatchId;
          const pending = batch.items.filter((i) => i.decision === 'pending').length;
          return (
            <button
              key={batch.id}
              onClick={() => setActiveBatchId(batch.id)}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium transition-all ${
                isActive
                  ? 'bg-slate-900 text-white'
                  : 'bg-white border border-slate-200 text-slate-600 hover:bg-slate-50'
              }`}
            >
              <span>{batch.weekLabel}</span>
              {batch.status === 'open' ? (
                <span className={`text-[10px] px-1.5 py-0.5 rounded-full ${
                  isActive ? 'bg-white/20 text-white' : 'bg-amber-100 text-amber-700'
                }`}>
                  {pending} pending
                </span>
              ) : (
                <Lock size={12} class